README.md
recipes/trace-filtering/README.md
recipes/trace-filtering/collector-config.yaml

It filters by the service name, which has been consistent across the applications.  I've opted to filter out all server spans.  That way, we keep the root span in the tree if we are viewing them in a UI.
I tested this with all three sample apps.

Add filtering example

---

sample-apps/java/README.md
sample-apps/nodejs/README.md
sample-apps/python/README.md

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/11.  Now, after I install an application, I know how to see the spans from that app.
Also, fixes the link to #auto-instrumenting-applications.

give instructions on next steps after sample app installation

---

collector-config.yaml
recipes/cloud-trace/collector-config.yaml

fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/8
I verified that the logging exporter outputs detailed trace information in both samples.

All logging processors use logLevel: debug so users can see span details

---

recipes/cloud-trace/README.md
sample-apps/nodejs-java/k8s/app.yaml
sample-apps/nodejs-java/k8s/service.yaml

Update Cloud Trace readme with troubleshooting for ServiceAccount annotation

---

README.md

Fixes #29 
Thanks to https://github.com/open-telemetry/opentelemetry-operator/issues/100#issuecomment-846125541 for documenting this solution. I was able to reproduce the issue in a private GKE autopilot cluster and applying this fix resolved the issue and I was able to deploy a collector.

Add note on firewall rules for private clusters

---

collector-config.yaml
recipes/cloud-trace/collector-config.yaml
recipes/resource-detection/collector-config.yaml
recipes/trace-enhancements/collector-config-resource-detection.yaml
recipes/trace-enhancements/collector-config.yaml
recipes/trace-filtering/collector-config.yaml

solves the following error:
error decoding 'exporters': error reading configuration for "logging": 1 error(s) decoding: unknown fields logLevel

fixed case for key loglevel on all configs

---

README.md
sample-apps/README.md
sample-apps/go/Makefile
sample-apps/go/README.md
sample-apps/go/app/Dockerfile
sample-apps/go/app/go.mod
sample-apps/go/app/main.go
sample-apps/go/k8s/app.yaml
sample-apps/go/k8s/service.yaml
sample-apps/go/server/Dockerfile
sample-apps/go/server/go.mod
sample-apps/go/server/main.go

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/30

Add Go sample app

---

recipes/daemonset-and-deployment/README.md
recipes/daemonset-and-deployment/daemonset-collector-config.yaml
recipes/daemonset-and-deployment/deployment-collector-config.yaml

This is a _very_ simple example, which just demonstrates forwarding from one collector to another.  I will follow-up with any additional requested features.

Add example of a daemonset forwarding to a deployment

---

sample-apps/go/server/main.go
sample-apps/java/service/src/main/java/com/google/example/service/Main.java
sample-apps/nodejs/server.js
sample-apps/python/requirements.txt
sample-apps/python/server.py

- Fix an issue in Python example where `requests` was not required, so `app.py` was broken.
- Add new `NEXT_SERVER` config to all example apps so that users can set up a "chain" or example applications easily.
Note: The new functionality is not yet documented.

Update all sample apps to delegate to NEXT_SERVER env variable.

---

README.md
recipes/README.md
recipes/trace-remote-sampling/README.md
recipes/trace-remote-sampling/collector-config.yaml
recipes/trace-remote-sampling/instrumentation.yaml
recipes/trace-remote-sampling/remote-sampling-config.yaml

I wasn't sure how much detail to get into with configuring Jaeger itself, let me know if the README should walk into how to turn on/off services.
kudos to @aabmass for the original example, modified here to fit opentelemetry-operator

Add a jaeger remote sampling recipe.

---

recipes/beyla/README.md
recipes/cloud-trace/README.md
recipes/daemonset-and-deployment/README.md

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/25
The recipes need to be deployed before the OpenTelemetryCollector can be annotated.

fix documentation to annotate the OpenTelemetryCollector

---

README.md
recipes/beyla/README.md
recipes/beyla/beyla-daemonset.yaml
recipes/beyla/collector-config.yaml
recipes/cloud-trace/collector-config.yaml
recipes/daemonset-and-deployment/daemonset-collector-config.yaml
recipes/daemonset-and-deployment/deployment-collector-config.yaml
recipes/resource-detection/collector-config.yaml
recipes/trace-enhancements/collector-config-resource-detection.yaml
recipes/trace-enhancements/collector-config.yaml
recipes/trace-filtering/collector-config.yaml
recipes/trace-remote-sampling/collector-config.yaml

Beyla renamed some config when it released v1.0.  This fixes that, and also pins image versions so examples don't break in the future.  It does mean we need to periodically bump image versions, but that seems preferable to users trying and failing to use samples.

Fix beyla example, and pin versions

---

recipes/beyla/beyla-daemonset.yaml
recipes/beyla/collector-config.yaml

the protocol is inferred, some permissions were not required, and we don't use a prometheus exporters.

Remove unnecessary beyla config, move to spanmetrics-based golden signals

---

recipes/beyla/collector-config.yaml

This makes the http metrics show up in the GKE in-context observability tab:

update beyla sample to use prometheus conventions

---

recipes/beyla/graphgen/main.go

- Add `-queryWindow` flag so you can change over how long metrics are gathered
- Remove unneeded labels from query to prevent duplicate edges

Beyla recipe - add flag for servicegraph query window

---

recipes/beyla/beyla-daemonset.yaml
recipes/beyla/collector-config.yaml
recipes/beyla/graphgen/internal/query.go
recipes/beyla/graphgen/internal/query_test.go
recipes/beyla/graphgen/main.go

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/61
By increasing the exporter cache length.
Also:
* Adapts to the stable HTTP semantic conventions.
* Sets only TRACES endpoint to remove errors from beyla when it attempts to export metrics.

Update beyla to the stable release

---

sample-apps/java/buildSrc/src/main/kotlin/com.google.example.java-common-conventions.gradle.kts

Allows the Java sample to reliably run on machines with Java 11+
Issue reported in #75

Set source and target compatibility for gradle to Java 11

---

recipes/beyla/beyla-daemonset.yaml

part of https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/78
Tested manually

Use default runtime seccomp profile and drop unnecessary capabilities

---

recipes/beyla-golden-signals/README.md
recipes/beyla-golden-signals/beyla-daemonset.yaml
recipes/beyla-golden-signals/collector-config.yaml
recipes/beyla-golden-signals/rbac.yaml
recipes/beyla/collector-config.yaml

I am splitting the Beyla sample, which currently has both golden metrics and service graph metrics into two separate samples. This PR splits out the golden metrics and the service graph will come next.
- Copied files
- Updated readme, removing references to Cloud Trace
- Removed service graph from collector config

Split Beyla golden metrics sample out

---

recipes/beyla-golden-signals/beyla-daemonset.yaml

See https://grafana.com/docs/beyla/latest/configure/options/#discovery-services-section
This prevents tracing non-pod processes running on nodes and filters out a lot of junk streams. Kubelet runs short lived scripts (e.g. health checks) that generate a lot of cardinality which leaks memory.
Along with upgrading beyla to 1.3.3, this gives better performance than the `spanmetrics` connector approach used previously:
- Fixed memory/CPU leak from cardinality growth (was affecting beyla and the collector)
- Beyla agent uses ~half as much memory (possibly improved due to version upgrades)
- CPU usage is on par with span metrics for both collector and beyla

Use Beyla's k8s service discovery instead of BEYLA_SYSTEM_WIDE

---

recipes/host-and-kubelet-metrics/README.md
recipes/host-and-kubelet-metrics/collector-config.yaml

It requires disabling the target_info metric because of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/834

Add hostmetrics and kubeletstats samples

---

recipes/beyla-golden-signals/beyla-daemonset.yaml
recipes/beyla-service-graph/beyla-daemonset.yaml

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operator-sample/issues/78
Builds on https://github.com/grafana/beyla/pull/741.  This uses a privileged init container to mount the bpf filesystem, and then does not need SYS_ADMIN when running.
I manually tested that this works for the in-context golden signals, and also that graphgen still produces the correct service graph.

Update beyla and remove sys_admin

---

recipes/beyla-golden-signals/gce/README.md
recipes/beyla-golden-signals/gce/beyla-config.yaml
recipes/beyla-golden-signals/gce/install-beyla.sh
recipes/beyla-golden-signals/gce/run-sample-app.sh

Updates the sample to use a config file instead of environment variables. Config file can be used to specify service discovery section, which allows the user to group multiple services running on the same VM instance in a single namespace and also provide names to services based on their `exe_path`.
*Note: Environment variables can be used in combination with the config-file, but have been removed in this PR to avoid confusion.*
- Ran the updated scripts with the updated instructions to generate the expected results.

Update GCE Beyla sample to use config file

---

.gitmodules
recipes/self-managed-otlp-ingest/README.md
recipes/self-managed-otlp-ingest/instrumentation.yaml
recipes/self-managed-otlp-ingest/k8s/kustomization.yaml
recipes/self-managed-otlp-ingest/k8s/quickstart-app.yaml
recipes/self-managed-otlp-ingest/k8s/quickstart-traffic.yaml
recipes/self-managed-otlp-ingest/setup-application.sh
recipes/self-managed-otlp-ingest/traffic/hey.Dockerfile

This PR adds a recipe to showcase the use of OpenTelemetry Operator with self managed OTLP collector configured to export to Google Cloud.
The operator adds and manages the instrumentation for the sample Java app (instrumentation-quickstart app).
The instrumentation is configured to export traces to the self-managed collector.

Add recipe for OTLP k8s ingest with auto-instrumentation

---

recipes/self-managed-otlp-ingest/traffic/cloudbuild-hey.yaml

Adds a configuration to allow building the 'hey' utility on Google Cloud Build. The config file is configured to read environment variables and push the built image to Google Artifact Registry.
- Ran gcloud builds submit --config <(envsubst < cloudbuild-hey.yaml) . to successfully build and push the image to Google Artifact Registry.

Add GCB config for hey
